"""Initial

Revision ID: e7ea64d40343
Revises: 
Create Date: 2021-01-08 16:56:24.841680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ea64d40343'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('cryptoType', sa.String(length=100), nullable=False),
    sa.Column('postDate', sa.Integer(), nullable=False),
    sa.Column('priceTarget', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('accumulateRange', sa.String(length=300), nullable=False),
    sa.Column('sellingTargets', sa.String(length=300), nullable=False),
    sa.Column('stopLoss', sa.Float(), nullable=False),
    sa.Column('entryZone', sa.String(length=300), nullable=False),
    sa.Column('currentAsk', sa.Float(), nullable=False),
    sa.Column('target1', sa.Float(), nullable=False),
    sa.Column('target2', sa.Float(), nullable=False),
    sa.Column('target3', sa.Float(), nullable=False),
    sa.Column('volume', sa.String(length=300), nullable=True),
    sa.Column('term', sa.String(length=20), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('cryptoType', 'postDate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal')
    # ### end Alembic commands ###
